typography_spectrum: 0.07939115539193153
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.3400290752761066
  lightness: 0.7060501440428197
  saturation: 0.98443896882236
  rhythmicContrast: 0.5759442674461752
opengraph:
  image: null
  type: Page
  appId: '267040383327385'
layout_spectrum: 0.6788736882153898
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: 'Erinn Wenrich, RA NCARB'
  email: erinn@brandywinestudio.com
  url: www.brandywinestudio.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9d879ab0-ff34-4e48-b4e6-f6b03c5bc5cb.png
name: Brandywine Studio LLC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about me
    id: 3b7622c1-81f7-4f80-9ab4-302da5918642
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/brandywinestudio?ref=hl'
    type: external
  - name: Houzz
    url: 'http://www.houzz.com/pro/brandywinestudio'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/brandywinestudio/?hl=en'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/erinnwenrichra/'
    type: external
  - name: Pinterest
    url: 'https://www.pinterest.com/erinnwenrich/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/erinnwenrich'
    type: external
favicon: null
title: love the space you're in
description: architecture | interiors
purpose: []
