typography_spectrum: 0.7781056452076882
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.11943485797382891
  lightness: 0.5467420574277639
  saturation: 0.7130713576916605
  rhythmicContrast: 0.5946563249453902
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7578612370416522
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: 'Erinn Wenrich, RA NCARB'
  email: erinn@brandywinestudio.com
  url: www.brandywinestudio.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f6f44895-0ba8-462e-941d-31f7988c6e87.jpg
name: Brandywine Studio LLC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about me
    id: 3b7622c1-81f7-4f80-9ab4-302da5918642
    type: content
favicon: null
title: love the space you're in
description: architecture | interiors
purpose: []
