layout_spectrum: 0.7578612370416522
typography_spectrum: 0.7781056452076882
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.11943485797382891
  lightness: 0.5467420574277639
  saturation: 0.7130713576916605
  rhythmicContrast: 0.5946563249453902
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Brandywine Studio LLC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Portfolio
    url: 'http://www.houzz.com/pro/brandywinestudio'
    type: external
  - name: Pinterest
    url: 'https://www.pinterest.com/erinnwenrich/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/brandywinestudio/'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/brandywinestudio/'
    type: external
favicon: null
title: love the space you're in
description: architecture | interiors
purpose: []
