typography_spectrum: 0.40147722768597305
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7847063336521387
  lightness: 0.22416105633601546
  saturation: 0.6694436469115317
  rhythmicContrast: 0.9493584104347974
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7578612370416522
analytics:
  google: null
  facebook: null
  twitter: null
name: Brandywine Studio LLC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Portfolio
    url: 'http://www.houzz.com/pro/brandywinestudio'
    type: external
  - name: Pinterest
    url: 'https://www.pinterest.com/erinnwenrich/'
    type: external
favicon: null
title: love the space you're in
description: architecture | interiors
purpose: []
